services:
  postgres:
    image: postgres:latest
    networks:
      - external-net
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5434:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  load_balancer:
    image: cloud-service
    ports:
      - "8080:8080"
    environment:
      ENV: "load_balancer"
      LOAD_BALANCER_STRATEGY: ${LOAD_BALANCER_STRATEGY}
      BASE_URL: "http://load_balancer:8080"
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESQL_CONNECTION_STRING: ${POSTGRESQL_CONNECTION_STRING}
      BACKEND_URLS: ${BACKEND_URLS}
    networks:
      - external-net
    depends_on:
      postgres:
        condition: service_healthy
      backend1:
        condition: service_started
      backend2:
        condition: service_started
      backend3:
        condition: service_started

  backend1:
    image: cloud-service
    environment:
      ENV: "common"
      HTTP_ADDR: "0.0.0.0:8081"
      BASE_URL: "http://backend1:8081"
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESQL_CONNECTION_STRING: ${POSTGRESQL_CONNECTION_STRING}
    networks:
      - external-net
    depends_on:
      - postgres

  backend2:
    image: cloud-service
    environment:
      ENV: "common"
      HTTP_ADDR: "0.0.0.0:8082"
      BASE_URL: "http://backend2:8082"
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESQL_CONNECTION_STRING: ${POSTGRESQL_CONNECTION_STRING}
    networks:
      - external-net
    depends_on:
      - postgres

  backend3:
    image: cloud-service
    environment:
      ENV: "common"
      HTTP_ADDR: "0.0.0.0:8083"
      BASE_URL: "http://backend3:8083"
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESQL_CONNECTION_STRING: ${POSTGRESQL_CONNECTION_STRING}
    networks:
      - external-net
    depends_on:
      - postgres

volumes:
  db-data:

networks:
  external-net:
    external: true
